---

- name: SystemD Environment vars file
  template:
    src:   "consul-environment-vars.j2"
    dest: "{{ consul_environment_file }}"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode:  "0644"
  notify: consul restart

- name: Consul Configuration
  template:
    src:   "config.{{consul_config_ext}}.j2"
    dest:  "{{consul_config_dir}}/{{item.key}}.{{consul_config_ext}}"
    owner: "{{consul_user}}"
    group: "{{consul_group}}"
    mode:  "0644"
    #validate: "{{consul_bin}} configtest -config-file {{consul_config_dir}}/%s"
  with_dict: "{{consul_config}}"
  notify: consul restart
  loop_control:
    label: "{{item.key}}"

- name: Consul Logrotate configuration
  copy:
    dest: "/etc/logrotate.d/consul"
    content: "{{consul_logrotate_config}}"
    owner: "root"
    group: "root"
    mode: "0644"
  when: consul_logrotate_enabled

# vi:ts=2:sw=2:et:ft=yaml
