---

- name: Include OS Family vars
  include_vars: "{{ansible_os_family}}.yml"
  tags: always

- include: user.yml
  when: consul_create_user
  tags: consul_user

- include: dirs.yml
  tags: consul_dirs

- include: install.yml
  tags: consul_install

- include: config.yml
  tags: consul_config

- include: service.yml
  tags: consul_service

# vi:ts=2:sw=2:et:ft=yaml
