---

- name: Include OS Family vars
  include_vars: "{{ ansible_os_family }}.yml"
  tags: always

- include: user.yml
  when: consul_create_user
  tags: consul_user

- include: dirs.yml
  tags: consul_dirs

- include: install.yml
  tags: consul_install

- include: ui.yml
  when: consul_legacy_ui_enabled
  tags: consul_legacy_ui

- include: config.yml
  tags: consul_config

- name: Consul Init Script
  template:
    src: "etc/init.d/consul.{{ ansible_os_family }}.j2"
    dest: /etc/init.d/consul
    owner: root
    group: root
    mode: "0755"
  tags: consul_initscript

- name: Enable Consul at boot
  service:
    name: consul
    enabled: yes
    state: "{{  (consul_started) | ternary('started', 'stopped') }}"
  when: consul_start_at_boot

# vi:ts=2:sw=2:et:ft=yaml
