---

- name: Consul SystemD Service
  template:
    src:   "systemd/consul.service.j2"
    dest:  "{{consul_systemd_prefix}}/consul.service"
    owner: root
    group: root
    mode:  "0644"
  register: consul_systemd_unit

- name: Reload Systemd
  systemd:
    daemon_reload: yes
  when: consul_systemd_unit is changed

# vi:ts=2:sw=2:et:ft=yaml
